name: "Terraform Tear Down"

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'information'
        type: choice
        options:
          - information
          - debug
          - warning
          - critical
permissions:
  id-token: write
  contents: read
  pull-requests: write
env:
  TF_LOG: DEBUG
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ROUTE53_ZONE: ${{ secrets.ROUTE53_HOSTED_ZONE }}
  ROUTE53_RECORD: ${{ secrets.ROUTE53_RECORD }}
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.2

      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" 

      - name: Terraform Destroy
        run: terraform destroy -var="domain=${ROUTE53_ZONE}" -var="record=${ROUTE53_RECORD}" -auto-approve